### PR TITLE
Added Dockerfile and Travis automation

### PR DESCRIPTION
**Pull request by nathan-weinberg**
See below comments for details

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
@mpryc Do we have some way to test this?

**Comment by mpryc** [comment]
Current implementation will trigger build on every PR that is in other projects such as:
  https://github.com/openstack-k8s-operators/nova-operator/blob/master/.travis.yml
  https://github.com/openstack-k8s-operators/compute-node-operator/blob/master/.travis.yml

This should not happen and after offline talk with Nathat we agreed on the following workflow:

 PR on github under openstack-k8s-operators/openstack-k8s-operators-ci will trigger travis job.

 That trigger will only work when Dockerfile responsible for building toolbox quay.io image is touched within that PR.

 Then travis CI will trigger quay.io image build with webhook between travis <-> quay, similarly to the project:
  https://github.com/lkiesow/automated-quay.io-deployment

This will allow clean path of build process and manual triggers using travis CI as quay webook to the github do not allow manual triggers.

**Comment by nathan-weinberg** [comment]
@mpryc Good point, we may want to do a depth of 2 just to be safe (no real drawbacks)

**Comment by nathan-weinberg** [comment]
@mpryc Looks like the job succeeded in terms of not running on a pull request, but I can't guarantee Travis will trigger on merge

We can discuss more in our meeting tomorrow

**Pull request merged**
